# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drawing_dto.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "maptool.DrawnElementDto" do
    optional :drawable, :message, 1, "maptool.DrawableDto"
    optional :pen, :message, 2, "maptool.PenDto"
  end
  add_message "maptool.PenDto" do
    optional :foreground_mode, :enum, 1, "maptool.PenDto.mode"
    optional :foreground_color, :message, 2, "maptool.DrawablePaintDto"
    optional :background_mode, :enum, 3, "maptool.PenDto.mode"
    optional :background_color, :message, 4, "maptool.DrawablePaintDto"
    optional :thickness, :float, 5
    optional :eraser, :bool, 6
    optional :square_cap, :bool, 7
    optional :opacity, :float, 8
  end
  add_enum "maptool.PenDto.mode" do
    value :MODE_SOLID, 0
    value :MODE_TRANSPARENT, 1
  end
  add_message "maptool.DrawableDto" do
    oneof :drawable_type do
      optional :shape_drawable, :message, 1, "maptool.ShapeDrawableDto"
      optional :rectangle_drawable, :message, 2, "maptool.RectangleDrawableDto"
      optional :oval_drawable, :message, 3, "maptool.OvalDrawableDto"
      optional :cross_drawable, :message, 4, "maptool.CrossDrawableDto"
      optional :drawn_label, :message, 5, "maptool.DrawnLabelDto"
      optional :line_segment, :message, 6, "maptool.LineSegmentDrawableDto"
      optional :drawables_group, :message, 7, "maptool.DrawablesGroupDto"
      optional :radius_cell_template, :message, 8, "maptool.RadiusCellTemplateDto"
      optional :line_cell_template, :message, 9, "maptool.LineCellTemplateDto"
      optional :radius_template, :message, 10, "maptool.RadiusTemplateDto"
      optional :burst_template, :message, 11, "maptool.BurstTemplateDto"
      optional :cone_template, :message, 12, "maptool.ConeTemplateDto"
      optional :blast_template, :message, 13, "maptool.BlastTemplateDto"
      optional :line_template, :message, 14, "maptool.LineTemplateDto"
      optional :wall_template, :message, 15, "maptool.WallTemplateDto"
    end
  end
  add_message "maptool.WallTemplateDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :zoneId, :string, 4
    optional :vertex, :message, 5, "maptool.IntPointDto"
    optional :radius, :int32, 6
    optional :mouse_slope_greater, :bool, 7
    optional :path_vertex, :message, 8, "maptool.IntPointDto"
    optional :double_wide, :bool, 9
    repeated :points, :message, 10, "maptool.IntPointDto"
  end
  add_message "maptool.LineTemplateDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :zoneId, :string, 4
    optional :vertex, :message, 5, "maptool.IntPointDto"
    optional :radius, :int32, 6
    optional :mouse_slope_greater, :bool, 7
    optional :quadrant, :string, 8
    optional :path_vertex, :message, 9, "maptool.IntPointDto"
    optional :double_wide, :bool, 10
  end
  add_message "maptool.BlastTemplateDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :zoneId, :string, 4
    optional :vertex, :message, 5, "maptool.IntPointDto"
    optional :radius, :int32, 6
    optional :direction, :string, 7
    optional :offset_x, :int32, 8
    optional :offset_y, :int32, 9
  end
  add_message "maptool.ConeTemplateDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :zoneId, :string, 4
    optional :vertex, :message, 5, "maptool.IntPointDto"
    optional :radius, :int32, 6
    optional :direction, :string, 7
  end
  add_message "maptool.BurstTemplateDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :zoneId, :string, 4
    optional :vertex, :message, 5, "maptool.IntPointDto"
    optional :radius, :int32, 6
  end
  add_message "maptool.RadiusTemplateDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :zoneId, :string, 4
    optional :vertex, :message, 5, "maptool.IntPointDto"
    optional :radius, :int32, 6
  end
  add_message "maptool.LineCellTemplateDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :zoneId, :string, 4
    optional :vertex, :message, 5, "maptool.IntPointDto"
    optional :radius, :int32, 6
    optional :mouse_slope_greater, :bool, 7
    optional :quadrant, :string, 8
    optional :path_vertex, :message, 9, "maptool.IntPointDto"
  end
  add_message "maptool.RadiusCellTemplateDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :zoneId, :string, 4
    optional :vertex, :message, 5, "maptool.IntPointDto"
    optional :radius, :int32, 6
  end
  add_message "maptool.DrawablesGroupDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    repeated :drawn_elements, :message, 4, "maptool.DrawnElementDto"
  end
  add_message "maptool.LineSegmentDrawableDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    repeated :points, :message, 4, "maptool.IntPointDto"
    optional :width, :float, 5
    optional :square_cap, :bool, 6
  end
  add_message "maptool.DrawnLabelDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :bounds, :message, 4, "maptool.RectangleDto"
    optional :text, :string, 5
    optional :font, :string, 6
  end
  add_message "maptool.RectangleDrawableDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :start_point, :message, 4, "maptool.IntPointDto"
    optional :end_point, :message, 5, "maptool.IntPointDto"
  end
  add_message "maptool.OvalDrawableDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :start_point, :message, 4, "maptool.IntPointDto"
    optional :end_point, :message, 5, "maptool.IntPointDto"
  end
  add_message "maptool.CrossDrawableDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :start_point, :message, 4, "maptool.IntPointDto"
    optional :end_point, :message, 5, "maptool.IntPointDto"
  end
  add_message "maptool.ShapeDrawableDto" do
    optional :id, :string, 1
    optional :layer, :string, 2
    optional :name, :message, 3, "google.protobuf.StringValue"
    optional :shape, :message, 4, "maptool.ShapeDto"
    optional :use_anti_aliasing, :bool, 5
  end
  add_message "maptool.ShapeDto" do
    oneof :shape_type do
      optional :rectangle, :message, 1, "maptool.RectangleDto"
      optional :area, :message, 2, "maptool.AreaDto"
      optional :polygon, :message, 3, "maptool.PolygonDto"
      optional :ellipse, :message, 4, "maptool.EllipseDto"
    end
  end
  add_message "maptool.AreaDto" do
    optional :winding, :enum, 1, "maptool.AreaDto.WindingRule"
    repeated :segments, :message, 2, "maptool.SegmentDto"
  end
  add_enum "maptool.AreaDto.WindingRule" do
    value :EVEN_ODD, 0
    value :NON_ZERO, 1
  end
  add_message "maptool.SegmentDto" do
    oneof :segment_type do
      optional :move_to, :message, 1, "maptool.MoveToSegment"
      optional :line_to, :message, 2, "maptool.LineToSegment"
      optional :quad_to, :message, 3, "maptool.QuadToSegment"
      optional :cubic_to, :message, 4, "maptool.CubicToSegment"
      optional :close, :message, 5, "maptool.CloseSegment"
    end
  end
  add_message "maptool.MoveToSegment" do
    optional :point_0, :message, 1, "maptool.DoublePointDto"
  end
  add_message "maptool.LineToSegment" do
    optional :point_0, :message, 1, "maptool.DoublePointDto"
  end
  add_message "maptool.QuadToSegment" do
    optional :point_0, :message, 1, "maptool.DoublePointDto"
    optional :point_1, :message, 2, "maptool.DoublePointDto"
  end
  add_message "maptool.CubicToSegment" do
    optional :point_0, :message, 1, "maptool.DoublePointDto"
    optional :point_1, :message, 2, "maptool.DoublePointDto"
    optional :point_2, :message, 3, "maptool.DoublePointDto"
  end
  add_message "maptool.CloseSegment" do
  end
  add_message "maptool.IntPointDto" do
    optional :x, :int32, 1
    optional :y, :int32, 2
  end
  add_message "maptool.DoublePointDto" do
    optional :x, :double, 1
    optional :y, :double, 2
  end
  add_message "maptool.PolygonDto" do
    repeated :points, :message, 1, "maptool.IntPointDto"
  end
  add_message "maptool.RectangleDto" do
    optional :x, :int32, 1
    optional :y, :int32, 2
    optional :width, :int32, 3
    optional :height, :int32, 4
  end
  add_message "maptool.EllipseDto" do
    optional :x, :float, 1
    optional :y, :float, 2
    optional :width, :float, 3
    optional :height, :float, 4
  end
  add_message "maptool.DrawablePaintDto" do
    oneof :paint_type do
      optional :color_paint, :message, 1, "maptool.DrawableColorPaintDto"
      optional :texture_paint, :message, 2, "maptool.DrawableTexturePaintDto"
    end
  end
  add_message "maptool.DrawableColorPaintDto" do
    optional :color, :int32, 1
  end
  add_message "maptool.DrawableTexturePaintDto" do
    optional :asset_id, :string, 1
    optional :scale, :double, 2
  end
end

module Maptool
  DrawnElementDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.DrawnElementDto").msgclass
  PenDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PenDto").msgclass
  PenDto::Mode = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PenDto.mode").enummodule
  DrawableDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.DrawableDto").msgclass
  WallTemplateDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.WallTemplateDto").msgclass
  LineTemplateDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LineTemplateDto").msgclass
  BlastTemplateDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.BlastTemplateDto").msgclass
  ConeTemplateDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ConeTemplateDto").msgclass
  BurstTemplateDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.BurstTemplateDto").msgclass
  RadiusTemplateDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RadiusTemplateDto").msgclass
  LineCellTemplateDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LineCellTemplateDto").msgclass
  RadiusCellTemplateDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RadiusCellTemplateDto").msgclass
  DrawablesGroupDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.DrawablesGroupDto").msgclass
  LineSegmentDrawableDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LineSegmentDrawableDto").msgclass
  DrawnLabelDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.DrawnLabelDto").msgclass
  RectangleDrawableDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RectangleDrawableDto").msgclass
  OvalDrawableDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.OvalDrawableDto").msgclass
  CrossDrawableDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.CrossDrawableDto").msgclass
  ShapeDrawableDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ShapeDrawableDto").msgclass
  ShapeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ShapeDto").msgclass
  AreaDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AreaDto").msgclass
  AreaDto::WindingRule = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AreaDto.WindingRule").enummodule
  SegmentDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SegmentDto").msgclass
  MoveToSegment = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.MoveToSegment").msgclass
  LineToSegment = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LineToSegment").msgclass
  QuadToSegment = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.QuadToSegment").msgclass
  CubicToSegment = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.CubicToSegment").msgclass
  CloseSegment = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.CloseSegment").msgclass
  IntPointDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.IntPointDto").msgclass
  DoublePointDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.DoublePointDto").msgclass
  PolygonDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PolygonDto").msgclass
  RectangleDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RectangleDto").msgclass
  EllipseDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.EllipseDto").msgclass
  DrawablePaintDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.DrawablePaintDto").msgclass
  DrawableColorPaintDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.DrawableColorPaintDto").msgclass
  DrawableTexturePaintDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.DrawableTexturePaintDto").msgclass
end
