# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamedata.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "maptool.GameDataValueDto" do
    optional :name, :string, 1
    oneof :value do
      optional :json_value, :string, 2
      optional :boolean_value, :bool, 3
      optional :long_value, :int64, 4
      optional :string_value, :string, 5
      optional :asset_value, :string, 6
      optional :double_value, :double, 7
      optional :undefined_json_array_value, :bool, 8
      optional :undefined_json_object_value, :bool, 9
      optional :undefined_boolean_value, :bool, 10
      optional :undefined_long_value, :bool, 11
      optional :undefined_string_value, :bool, 12
      optional :undefined_asset_value, :bool, 13
      optional :undefined_double_value, :bool, 14
      optional :undefined_value, :bool, 16
    end
  end
  add_message "maptool.GameDataDto" do
    optional :type, :string, 1
    optional :namespace, :string, 2
    repeated :values, :message, 3, "maptool.GameDataValueDto"
  end
  add_message "maptool.DataStoreDto" do
    optional :data_store_type, :string, 1
    repeated :data, :message, 2, "maptool.GameDataDto"
  end
end

module Maptool
  GameDataValueDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.GameDataValueDto").msgclass
  GameDataDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.GameDataDto").msgclass
  DataStoreDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.DataStoreDto").msgclass
end
