# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_transfer_objects.proto

require 'google/protobuf'

require_relative 'drawing_dto_pb'
require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "maptool.ServerPolicyDto" do
    optional :use_strict_token_management, :bool, 1
    optional :is_movement_locked, :bool, 2
    optional :is_token_editor_locked, :bool, 3
    optional :players_can_reveal_vision, :bool, 4
    optional :gm_reveals_vision_for_unowned_tokens, :bool, 5
    optional :use_individual_views, :bool, 6
    optional :restricted_impersonation, :bool, 7
    optional :players_receive_campaign_macros, :bool, 8
    optional :use_tool_tips_for_default_roll_format, :bool, 9
    optional :use_individual_FOW, :bool, 10
    optional :is_auto_reveal_on_movement, :bool, 11
    optional :include_owned_NPCs, :bool, 12
    optional :movement_metric, :enum, 13, "maptool.WalkerMetricDto"
    optional :using_astar_pathfinding, :bool, 14
    optional :vbl_blocks_move, :bool, 15
    optional :hide_map_select_ui, :bool, 16
    optional :lock_player_library, :bool, 17
  end
  add_message "maptool.CampaignDto" do
    optional :id, :string, 1
    optional :name, :string, 2
    optional :has_used_fog_toolbar, :message, 3, "google.protobuf.BoolValue"
    optional :properties, :message, 4, "maptool.CampaignPropertiesDto"
    optional :export_location, :message, 5, "maptool.LocationDto"
    map :export_settings, :string, :bool, 6
    optional :macro_button_last_index, :int32, 7
    optional :gm_macro_button_last_index, :int32, 8
    repeated :macro_button_properties, :message, 9, "maptool.MacroButtonPropertiesDto"
    repeated :zones, :message, 10, "maptool.ZoneDto"
    repeated :gm_macro_button_properties, :message, 11, "maptool.MacroButtonPropertiesDto"
  end
  add_message "maptool.LookupTableDto" do
    repeated :entries, :message, 1, "maptool.LookupEntryDto"
    optional :name, :string, 2
    optional :default_roll, :string, 3
    optional :table_image, :message, 4, "google.protobuf.StringValue"
    optional :visible, :bool, 5
    optional :allow_lookup, :bool, 6
    optional :pick_once, :bool, 7
  end
  add_message "maptool.LookupEntryDto" do
    optional :min, :int32, 1
    optional :max, :int32, 2
    optional :picked, :bool, 3
    optional :value, :message, 4, "google.protobuf.StringValue"
    optional :image_id, :message, 5, "google.protobuf.StringValue"
  end
  add_message "maptool.LightSourceDto" do
    repeated :lights, :message, 1, "maptool.LightDto"
    optional :name, :message, 2, "google.protobuf.StringValue"
    optional :id, :message, 3, "google.protobuf.StringValue"
    optional :type, :enum, 4, "maptool.LightSourceDto.LightTypeDto"
    optional :shape_type, :enum, 5, "maptool.ShapeTypeDto"
    optional :lumens, :int32, 6
    optional :scale_with_token, :bool, 7
  end
  add_enum "maptool.LightSourceDto.LightTypeDto" do
    value :NORMAL, 0
    value :AURA, 1
  end
  add_message "maptool.LightDto" do
    optional :paint, :message, 1, "maptool.DrawablePaintDto"
    optional :facing_offset, :double, 2
    optional :radius, :double, 3
    optional :arc_angle, :double, 4
    optional :shape, :enum, 5, "maptool.ShapeTypeDto"
    optional :is_gm, :bool, 6
    optional :owner_only, :bool, 7
  end
  add_message "maptool.LocationDto" do
    oneof :LocationTyp do
      optional :local_location, :message, 1, "maptool.LocalLocationDto"
      optional :ftp_location, :message, 2, "maptool.FtpLocationDto"
    end
  end
  add_message "maptool.LocalLocationDto" do
    optional :local_file, :string, 1
  end
  add_message "maptool.FtpLocationDto" do
    optional :user_name, :string, 1
    optional :host_name, :string, 2
    optional :path, :string, 3
    optional :binary, :bool, 4
  end
  add_message "maptool.CampaignPropertiesDto" do
    map :token_types, :string, :message, 1, "maptool.TokenPropertyListDto"
    optional :default_sight_type, :message, 2, "google.protobuf.StringValue"
    repeated :token_states, :message, 3, "maptool.BooleanTokenOverlayDto"
    repeated :token_bars, :message, 4, "maptool.BarTokenOverlayDto"
    map :character_sheets, :string, :string, 5
    optional :initiative_owner_permissions, :bool, 6
    optional :initiative_movementLock, :bool, 7
    optional :initiative_use_reverse_sort, :bool, 8
    optional :initiative_panel_buttons_disabled, :bool, 9
    map :light_sources, :string, :message, 10, "maptool.LightSourceListDto"
    repeated :remote_repositories, :string, 11
    repeated :lookup_tables, :message, 12, "maptool.LookupTableDto"
    repeated :sight_types, :message, 13, "maptool.SightTypeDto"
  end
  add_message "maptool.SightTypeDto" do
    optional :name, :string, 1
    optional :multiplier, :double, 2
    optional :personal_light_source, :message, 3, "maptool.LightSourceDto"
    optional :shape, :enum, 4, "maptool.ShapeTypeDto"
    optional :arc, :int32, 5
    optional :distance, :float, 6
    optional :offset, :int32, 7
    optional :scale_with_token, :bool, 8
  end
  add_message "maptool.TokenPropertyDto" do
    optional :name, :string, 1
    optional :short_name, :message, 2, "google.protobuf.StringValue"
    optional :high_priority, :bool, 3
    optional :owner_only, :bool, 4
    optional :gm_only, :bool, 5
    optional :default_value, :message, 6, "google.protobuf.StringValue"
  end
  add_message "maptool.TokenOverlayDto" do
    optional :name, :string, 1
    optional :order, :int32, 2
    optional :group, :message, 3, "google.protobuf.StringValue"
    optional :mouse_over, :bool, 4
    optional :opacity, :int32, 5
    optional :show_gm, :bool, 6
    optional :show_owner, :bool, 7
    optional :show_others, :bool, 8
  end
  add_message "maptool.BarTokenOverlayDto" do
    optional :common, :message, 1, "maptool.TokenOverlayDto"
    optional :increments, :int32, 2
    optional :side, :enum, 3, "maptool.BarTokenOverlayDto.SideDto"
    repeated :asset_ids, :string, 4
    optional :color, :int32, 5
    optional :bg_color, :int32, 6
    optional :thickness, :int32, 7
    optional :type, :enum, 8, "maptool.BarTokenOverlayDto.BarTokenOverlayTypeDto"
  end
  add_enum "maptool.BarTokenOverlayDto.SideDto" do
    value :TOP, 0
    value :BOTTOM, 1
    value :LEFT, 2
    value :RIGHT, 3
  end
  add_enum "maptool.BarTokenOverlayDto.BarTokenOverlayTypeDto" do
    value :MULTIPLE_IMAGE, 0
    value :SINGLE_IMAGE, 1
    value :DRAWN, 2
    value :TWO_TONE, 3
    value :TWO_IMAGES, 4
  end
  add_message "maptool.BooleanTokenOverlayDto" do
    optional :common, :message, 1, "maptool.TokenOverlayDto"
    optional :color, :int32, 2
    optional :stroke, :message, 3, "maptool.StrokeDto"
    optional :quadrant, :enum, 4, "maptool.QuadrantDto"
    optional :grid_size, :int32, 5
    optional :asset_id, :string, 6
    optional :type, :enum, 7, "maptool.BooleanTokenOverlayDto.BooleanTokenOverlayTypeDto"
  end
  add_enum "maptool.BooleanTokenOverlayDto.BooleanTokenOverlayTypeDto" do
    value :X, 0
    value :YIELD, 1
    value :O, 2
    value :COLOR_DOT, 3
    value :DIAMOND, 4
    value :TRIANGLE, 5
    value :CROSS, 6
    value :FLOW_COLOR_DOT, 7
    value :FLOW_DIAMOND, 8
    value :FLOW_COLOR_SQUARE, 9
    value :FLOW_YIELD, 10
    value :SHADED, 11
    value :IMAGE, 12
    value :FLOW_IMAGE, 13
    value :CORNER_IMAGE, 14
  end
  add_message "maptool.StrokeDto" do
    optional :width, :float, 1
    optional :cap, :enum, 2, "maptool.StrokeDto.CapDto"
    optional :join, :enum, 3, "maptool.StrokeDto.JoinDto"
  end
  add_enum "maptool.StrokeDto.CapDto" do
    value :CAP_BUTT, 0
    value :CAP_ROUND, 1
    value :CAP_SQUARE, 2
  end
  add_enum "maptool.StrokeDto.JoinDto" do
    value :JOIN_MITER, 0
    value :JOIN_ROUND, 1
    value :JOIN_BEVEL, 2
  end
  add_message "maptool.TokenPropertyListDto" do
    repeated :properties, :message, 1, "maptool.TokenPropertyDto"
  end
  add_message "maptool.LightSourceListDto" do
    repeated :light_sources, :message, 1, "maptool.LightSourceDto"
  end
  add_message "maptool.TokenDto" do
    optional :id, :string, 1
    optional :being_impersonated, :bool, 2
    optional :exposed_area_guid, :string, 3
    map :image_asset_map, :string, :string, 4
    optional :current_image_asset, :message, 5, "google.protobuf.StringValue"
    optional :x, :int32, 6
    optional :y, :int32, 7
    optional :z, :int32, 8
    optional :anchor_x, :int32, 9
    optional :anchor_y, :int32, 10
    optional :size_scale, :double, 11
    optional :last_x, :int32, 12
    optional :last_y, :int32, 13
    optional :last_path, :message, 14, "maptool.PathDto"
    optional :snap_to_scale, :bool, 15
    optional :width, :int32, 16
    optional :height, :int32, 17
    optional :iso_width, :int32, 18
    optional :iso_height, :int32, 19
    optional :scale_x, :double, 20
    optional :scale_y, :double, 21
    map :size_map, :string, :string, 22
    optional :snap_to_grid, :bool, 23
    optional :is_visible, :bool, 24
    optional :visible_only_to_owner, :bool, 25
    optional :vbl_color_sensitivity, :int32, 26
    optional :always_visible_tolerance, :int32, 27
    optional :is_always_visible, :bool, 28
    optional :vbl, :message, 29, "maptool.AreaDto"
    optional :hillVbl, :message, 65, "maptool.AreaDto"
    optional :pitVbl, :message, 66, "maptool.AreaDto"
    optional :mbl, :message, 67, "maptool.AreaDto"
    optional :name, :string, 30
    repeated :owner_list, :string, 31
    optional :owner_type, :int32, 32
    optional :token_shape, :string, 33
    optional :token_type, :string, 34
    optional :layer, :string, 35
    optional :property_type, :string, 36
    optional :facing, :message, 37, "google.protobuf.Int32Value"
    optional :halo_color, :message, 38, "google.protobuf.Int32Value"
    optional :vision_overlay_color, :message, 39, "google.protobuf.Int32Value"
    optional :token_opacity, :float, 40
    optional :speech_name, :string, 41
    optional :terrain_modifier, :double, 42
    optional :terrain_modifier_operation, :enum, 43, "maptool.TerrainModifierOperationDto"
    repeated :terrain_modifiers_ignored, :enum, 44, "maptool.TerrainModifierOperationDto"
    optional :is_flipped_x, :bool, 45
    optional :is_flipped_y, :bool, 46
    optional :is_flipped_iso, :bool, 47
    optional :charsheet_image, :message, 48, "google.protobuf.StringValue"
    optional :portrait_image, :message, 49, "google.protobuf.StringValue"
    repeated :light_sources, :message, 50, "maptool.AttachedLightSourceDto"
    optional :sight_type, :message, 51, "google.protobuf.StringValue"
    optional :has_sight, :bool, 52
    optional :has_image_table, :bool, 53
    optional :image_table_name, :message, 54, "google.protobuf.StringValue"
    optional :label, :message, 55, "google.protobuf.StringValue"
    optional :notes, :message, 56, "google.protobuf.StringValue"
    optional :gm_notes, :message, 57, "google.protobuf.StringValue"
    optional :gm_name, :message, 58, "google.protobuf.StringValue"
    map :state, :string, :message, 59, "maptool.TokenDto.State"
    map :properties, :string, :string, 60
    map :macro_properties, :int32, :message, 61, "maptool.MacroButtonPropertiesDto"
    map :speech, :string, :string, 62
    optional :hero_lab_data, :message, 63, "maptool.HeroLabDataDto"
    optional :allow_uri_access, :bool, 64
  end
  add_message "maptool.TokenDto.State" do
    oneof :state_type do
      optional :bool_value, :bool, 1
      optional :double_value, :double, 2
    end
  end
  add_enum "maptool.TokenDto.TokenShape" do
    value :TOP_DOWN, 0
    value :CIRCLE, 1
    value :SQUARE, 2
    value :FIGURE, 3
  end
  add_message "maptool.PathDto" do
    optional :point_type, :enum, 1, "maptool.PathDto.PointType"
    repeated :cells, :message, 2, "maptool.IntPointDto"
    repeated :waypoints, :message, 3, "maptool.IntPointDto"
  end
  add_enum "maptool.PathDto.PointType" do
    value :CELL_POINT, 0
    value :ZONE_POINT, 1
  end
  add_message "maptool.TerrainModifierOperationListDto" do
    repeated :modifiers, :enum, 1, "maptool.TerrainModifierOperationDto"
  end
  add_message "maptool.AttachedLightSourceDto" do
    optional :light_source_id, :string, 1
    optional :direction, :string, 2
  end
  add_message "maptool.MacroButtonPropertiesDto" do
    optional :macro_id, :string, 1
    optional :save_location, :string, 2
    optional :index, :int32, 3
    optional :color_key, :string, 4
    optional :hot_key, :string, 5
    optional :command, :string, 6
    optional :label, :string, 7
    optional :group, :string, 8
    optional :sortby, :string, 9
    optional :auto_execute, :bool, 10
    optional :include_label, :bool, 11
    optional :apply_to_tokens, :bool, 12
    optional :font_color_key, :string, 13
    optional :font_size, :string, 14
    optional :min_width, :string, 15
    optional :max_width, :string, 16
    optional :allow_player_edits, :bool, 17
    optional :tool_tip, :string, 18
    optional :display_hot_key, :bool, 19
  end
  add_message "maptool.MacroButtonPropertiesListDto" do
    repeated :macros, :message, 1, "maptool.MacroButtonPropertiesDto"
  end
  add_message "maptool.HeroLabDataDto" do
    optional :hero_lab_statblock_asset_id, :message, 1, "google.protobuf.StringValue"
    optional :name, :string, 2
    optional :summary, :message, 3, "google.protobuf.StringValue"
    optional :player_name, :message, 4, "google.protobuf.StringValue"
    optional :game_system, :message, 5, "google.protobuf.StringValue"
    optional :hero_lab_index, :message, 6, "google.protobuf.StringValue"
    optional :minion_master_index, :message, 7, "google.protobuf.StringValue"
    optional :minion_master_name, :message, 8, "google.protobuf.StringValue"
    optional :is_ally, :bool, 9
    optional :is_dirty, :bool, 10
    optional :is_minion, :bool, 11
    optional :portfolio_path, :message, 12, "google.protobuf.StringValue"
    map :hero_image_assets, :string, :string, 13
  end
  add_message "maptool.ScriptTypeDto" do
    oneof :type do
      optional :double_val, :double, 1
      optional :string_val, :string, 2
      optional :json_val, :string, 3
    end
  end
  add_message "maptool.TextMessageDto" do
    optional :channel, :int32, 1
    optional :target, :message, 2, "google.protobuf.StringValue"
    optional :message, :string, 3
    optional :source, :string, 4
    repeated :transform, :string, 5
  end
  add_message "maptool.PlayerDto" do
    optional :name, :string, 1
    optional :role, :string, 2
  end
  add_message "maptool.AssetDto" do
    optional :md5_key, :string, 1
    optional :name, :string, 2
    optional :extension, :string, 3
    optional :type, :enum, 4, "maptool.AssetDtoType"
    optional :data, :bytes, 5
  end
  add_message "maptool.LabelDto" do
    optional :id, :string, 1
    optional :label, :string, 2
    optional :x, :int32, 3
    optional :y, :int32, 4
    optional :show_background, :bool, 5
    optional :foreground_color, :int32, 6
  end
  add_message "maptool.ZoneDto" do
    optional :creation_time, :int64, 1
    optional :id, :string, 2
    optional :grid, :message, 3, "maptool.GridDto"
    optional :grid_color, :int32, 4
    optional :image_scale_x, :float, 5
    optional :image_scale_y, :float, 6
    optional :token_vision_distance, :int32, 7
    optional :units_per_cell, :double, 8
    optional :a_star_rounding, :enum, 9, "maptool.ZoneDto.AStarRoundingOptionsDto"
    repeated :topologyTypes, :enum, 10, "maptool.TopologyTypeDto"
    repeated :drawables, :message, 11, "maptool.DrawnElementDto"
    repeated :gm_drawables, :message, 12, "maptool.DrawnElementDto"
    repeated :object_drawables, :message, 13, "maptool.DrawnElementDto"
    repeated :background_drawables, :message, 14, "maptool.DrawnElementDto"
    repeated :labels, :message, 15, "maptool.LabelDto"
    repeated :tokens, :message, 16, "maptool.TokenDto"
    map :exposed_area_meta, :string, :message, 17, "maptool.AreaDto"
    optional :initiative, :message, 18, "maptool.InitiativeListDto"
    optional :exposed_area, :message, 19, "maptool.AreaDto"
    optional :has_fog, :bool, 20
    optional :fog_paint, :message, 21, "maptool.DrawablePaintDto"
    optional :topology, :message, 22, "maptool.AreaDto"
    optional :hill_vbl, :message, 23, "maptool.AreaDto"
    optional :pit_vbl, :message, 24, "maptool.AreaDto"
    optional :topology_terrain, :message, 25, "maptool.AreaDto"
    optional :background_paint, :message, 26, "maptool.DrawablePaintDto"
    optional :map_asset, :message, 27, "google.protobuf.StringValue"
    optional :boardPosition, :message, 28, "maptool.IntPointDto"
    optional :draw_board, :bool, 29
    optional :boardChanged, :bool, 30
    optional :name, :string, 31
    optional :player_alias, :message, 32, "google.protobuf.StringValue"
    optional :is_visible, :bool, 33
    optional :vision_type, :enum, 34, "maptool.ZoneDto.VisionTypeDto"
    optional :token_selection, :enum, 35, "maptool.ZoneDto.TokenSelectionDto"
    optional :height, :int32, 36
    optional :width, :int32, 37
  end
  add_enum "maptool.ZoneDto.TokenSelectionDto" do
    value :PC, 0
    value :NPC, 1
    value :ALL, 2
    value :GM, 3
  end
  add_enum "maptool.ZoneDto.VisionTypeDto" do
    value :OFF, 0
    value :DAY, 1
    value :NIGHT, 2
  end
  add_enum "maptool.ZoneDto.AStarRoundingOptionsDto" do
    value :NONE, 0
    value :CELL_UNIT, 1
    value :INTEGER, 2
  end
  add_message "maptool.InitiativeListDto" do
    repeated :tokens, :message, 1, "maptool.TokenInitiativeDto"
    optional :current, :int32, 2
    optional :round, :int32, 3
    optional :zone_id, :string, 4
    optional :hide_npc, :bool, 5
  end
  add_message "maptool.TokenInitiativeDto" do
    optional :token_id, :string, 1
    optional :holding, :bool, 2
    optional :state, :message, 3, "google.protobuf.StringValue"
  end
  add_message "maptool.GridDto" do
    optional :offset_x, :int32, 1
    optional :offset_y, :int32, 2
    optional :size, :int32, 3
    optional :cell_shape, :message, 4, "maptool.AreaDto"
    oneof :type do
      optional :square_grid, :message, 5, "maptool.SquareGridDto"
      optional :gridless_grid, :message, 6, "maptool.GridlessGridDto"
      optional :hex_grid, :message, 7, "maptool.HexGridDto"
      optional :isometric_grid, :message, 8, "maptool.IsometricGridDto"
    end
  end
  add_message "maptool.SquareGridDto" do
  end
  add_message "maptool.GridlessGridDto" do
  end
  add_message "maptool.IsometricGridDto" do
  end
  add_message "maptool.HexGridDto" do
    optional :vertical, :bool, 1
    optional :hex_ratio, :double, 2
    optional :edge_projection, :double, 3
    optional :minor_radius, :double, 4
    optional :edge_length, :double, 5
    optional :scaled_edge_projection, :double, 6
    optional :scaled_minor_radius, :double, 7
    optional :scaled_edge_length, :double, 8
    optional :last_scale, :double, 9
    optional :cellOffset, :message, 10, "maptool.IntPointDto"
  end
  add_message "maptool.AssetTransferHeaderDto" do
    optional :id, :string, 1
    optional :name, :string, 2
    optional :size, :int64, 3
  end
  add_message "maptool.AssetChunkDto" do
    optional :id, :string, 1
    optional :data, :bytes, 2
  end
  add_message "maptool.TokenPropertyValueDto" do
    oneof :value_type do
      optional :int_value, :int32, 1
      optional :bool_value, :bool, 2
      optional :string_value, :string, 3
      optional :double_value, :double, 4
      optional :macros, :message, 5, "maptool.MacroButtonPropertiesListDto"
      optional :light_source, :message, 6, "maptool.LightSourceDto"
      optional :area, :message, 7, "maptool.AreaDto"
      optional :string_values, :message, 8, "maptool.StringListDto"
      optional :grid, :message, 9, "maptool.GridDto"
      optional :token_foot_print, :message, 10, "maptool.TokenFootPrintDto"
      optional :topology_type, :string, 11
    end
  end
  add_message "maptool.StringListDto" do
    repeated :values, :string, 1
  end
  add_message "maptool.PointerDto" do
    optional :zone_guid, :string, 1
    optional :point, :message, 2, "maptool.IntPointDto"
    optional :direction, :double, 3
    optional :type, :string, 4
  end
  add_message "maptool.TransferableAddOnLibraryDto" do
    optional :namespace, :string, 1
    optional :version, :string, 2
    optional :asset_key, :string, 3
  end
  add_message "maptool.TokenFootPrintDto" do
    repeated :cell_set, :message, 1, "maptool.IntPointDto"
    optional :name, :string, 2
    optional :id, :string, 3
    optional :is_default, :bool, 4
    optional :scale, :double, 5
    optional :localize_name, :bool, 6
  end
  add_enum "maptool.ShapeTypeDto" do
    value :SQUARE, 0
    value :CIRCLE, 1
    value :CONE, 2
    value :HEX, 3
    value :GRID, 4
  end
  add_enum "maptool.QuadrantDto" do
    value :NORTH_EAST, 0
    value :NORTH_WEST, 1
    value :SOUTH_EAST, 2
    value :SOUTH_WEST, 3
  end
  add_enum "maptool.WalkerMetricDto" do
    value :NO_DIAGONALS, 0
    value :MANHATTAN, 1
    value :ONE_TWO_ONE, 2
    value :ONE_ONE_ONE, 3
  end
  add_enum "maptool.RoleDto" do
    value :PLAYER, 0
    value :GM, 1
  end
  add_enum "maptool.TopologyTypeDto" do
    value :WALL_VBL, 0
    value :HILL_VBL, 1
    value :PIT_VBL, 2
    value :MBL, 3
  end
  add_enum "maptool.GridTypeDto" do
    value :Square, 0
    value :Gridless, 1
    value :HexVertical, 2
    value :HexHorizontal, 3
    value :Isometric, 4
  end
  add_enum "maptool.TerrainModifierOperationDto" do
    value :NONE, 0
    value :MULTIPLY, 1
    value :ADD, 2
    value :BLOCK, 3
    value :FREE, 4
  end
  add_enum "maptool.AssetDtoType" do
    value :IMAGE, 0
    value :AUDIO, 1
    value :HTML, 2
    value :DATA, 3
    value :MARKDOWN, 4
    value :JAVASCRIPT, 5
    value :CSS, 6
    value :TEXT, 7
    value :JSON, 8
    value :XML, 9
    value :PDF, 10
    value :MTLIB, 11
    value :INVAlID, 12
  end
  add_enum "maptool.TokenUpdateDto" do
    value :setState, 0
    value :setAllStates, 1
    value :setPropertyType, 2
    value :setPC, 3
    value :setNPC, 4
    value :setLayer, 5
    value :setLayerShape, 6
    value :setShape, 7
    value :setSnapToScale, 8
    value :setSnapToGrid, 9
    value :setSnapToGridAndXY, 10
    value :setFootprint, 11
    value :setProperty, 12
    value :resetProperty, 13
    value :setZOrder, 14
    value :setFacing, 15
    value :clearAllOwners, 16
    value :setOwnedByAll, 17
    value :addOwner, 18
    value :setScaleX, 19
    value :setScaleY, 20
    value :setScaleXY, 21
    value :setNotes, 22
    value :setGMNotes, 23
    value :saveMacro, 24
    value :saveMacroList, 25
    value :deleteMacro, 26
    value :setX, 27
    value :setY, 28
    value :setXY, 29
    value :setHaloColor, 30
    value :setLabel, 31
    value :setName, 32
    value :setGMName, 33
    value :setVisible, 34
    value :setVisibleOnlyToOwner, 35
    value :setIsAlwaysVisible, 36
    value :setTokenOpacity, 37
    value :setTerrainModifier, 38
    value :setTerrainModifierOperation, 39
    value :setTerrainModifiersIgnored, 40
    value :setTopology, 41
    value :setImageAsset, 42
    value :setPortraitImage, 43
    value :setCharsheetImage, 44
    value :setLayout, 45
    value :clearLightSources, 46
    value :removeLightSource, 47
    value :addLightSource, 48
    value :setHasSight, 49
    value :setSightType, 50
    value :flipX, 51
    value :flipY, 52
    value :flipIso, 53
    value :setSpeechName, 54
    value :removeFacing, 55
  end
end

module Maptool
  ServerPolicyDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ServerPolicyDto").msgclass
  CampaignDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.CampaignDto").msgclass
  LookupTableDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LookupTableDto").msgclass
  LookupEntryDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LookupEntryDto").msgclass
  LightSourceDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LightSourceDto").msgclass
  LightSourceDto::LightTypeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LightSourceDto.LightTypeDto").enummodule
  LightDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LightDto").msgclass
  LocationDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LocationDto").msgclass
  LocalLocationDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LocalLocationDto").msgclass
  FtpLocationDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.FtpLocationDto").msgclass
  CampaignPropertiesDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.CampaignPropertiesDto").msgclass
  SightTypeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SightTypeDto").msgclass
  TokenPropertyDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TokenPropertyDto").msgclass
  TokenOverlayDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TokenOverlayDto").msgclass
  BarTokenOverlayDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.BarTokenOverlayDto").msgclass
  BarTokenOverlayDto::SideDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.BarTokenOverlayDto.SideDto").enummodule
  BarTokenOverlayDto::BarTokenOverlayTypeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.BarTokenOverlayDto.BarTokenOverlayTypeDto").enummodule
  BooleanTokenOverlayDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.BooleanTokenOverlayDto").msgclass
  BooleanTokenOverlayDto::BooleanTokenOverlayTypeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.BooleanTokenOverlayDto.BooleanTokenOverlayTypeDto").enummodule
  StrokeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.StrokeDto").msgclass
  StrokeDto::CapDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.StrokeDto.CapDto").enummodule
  StrokeDto::JoinDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.StrokeDto.JoinDto").enummodule
  TokenPropertyListDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TokenPropertyListDto").msgclass
  LightSourceListDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LightSourceListDto").msgclass
  TokenDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TokenDto").msgclass
  TokenDto::State = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TokenDto.State").msgclass
  TokenDto::TokenShape = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TokenDto.TokenShape").enummodule
  PathDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PathDto").msgclass
  PathDto::PointType = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PathDto.PointType").enummodule
  TerrainModifierOperationListDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TerrainModifierOperationListDto").msgclass
  AttachedLightSourceDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AttachedLightSourceDto").msgclass
  MacroButtonPropertiesDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.MacroButtonPropertiesDto").msgclass
  MacroButtonPropertiesListDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.MacroButtonPropertiesListDto").msgclass
  HeroLabDataDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.HeroLabDataDto").msgclass
  ScriptTypeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ScriptTypeDto").msgclass
  TextMessageDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TextMessageDto").msgclass
  PlayerDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PlayerDto").msgclass
  AssetDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AssetDto").msgclass
  LabelDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.LabelDto").msgclass
  ZoneDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ZoneDto").msgclass
  ZoneDto::TokenSelectionDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ZoneDto.TokenSelectionDto").enummodule
  ZoneDto::VisionTypeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ZoneDto.VisionTypeDto").enummodule
  ZoneDto::AStarRoundingOptionsDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ZoneDto.AStarRoundingOptionsDto").enummodule
  InitiativeListDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.InitiativeListDto").msgclass
  TokenInitiativeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TokenInitiativeDto").msgclass
  GridDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.GridDto").msgclass
  SquareGridDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SquareGridDto").msgclass
  GridlessGridDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.GridlessGridDto").msgclass
  IsometricGridDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.IsometricGridDto").msgclass
  HexGridDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.HexGridDto").msgclass
  AssetTransferHeaderDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AssetTransferHeaderDto").msgclass
  AssetChunkDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AssetChunkDto").msgclass
  TokenPropertyValueDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TokenPropertyValueDto").msgclass
  StringListDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.StringListDto").msgclass
  PointerDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PointerDto").msgclass
  TransferableAddOnLibraryDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TransferableAddOnLibraryDto").msgclass
  TokenFootPrintDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TokenFootPrintDto").msgclass
  ShapeTypeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ShapeTypeDto").enummodule
  QuadrantDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.QuadrantDto").enummodule
  WalkerMetricDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.WalkerMetricDto").enummodule
  RoleDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RoleDto").enummodule
  TopologyTypeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TopologyTypeDto").enummodule
  GridTypeDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.GridTypeDto").enummodule
  TerrainModifierOperationDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TerrainModifierOperationDto").enummodule
  AssetDtoType = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AssetDtoType").enummodule
  TokenUpdateDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.TokenUpdateDto").enummodule
end
