# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "maptool.AddOnLibraryDto" do
    optional :name, :string, 17
    optional :version, :string, 18
    optional :website, :string, 19
    optional :git_url, :string, 20
    repeated :authors, :string, 21
    optional :license, :string, 22
    optional :namespace, :string, 23
    optional :description, :string, 24
    optional :short_description, :string, 25
    optional :allowsUriAccess, :bool, 26
    optional :license_file, :string, 27
    optional :read_me_file, :string, 28
  end
  add_message "maptool.MTScriptPropertiesDto" do
    repeated :properties, :message, 1, "maptool.MTScriptPropertiesDto.Property"
  end
  add_message "maptool.MTScriptPropertiesDto.Property" do
    optional :filename, :string, 1
    optional :auto_execute, :bool, 2
    optional :description, :string, 3
  end
  add_message "maptool.AddOnLibraryListDto" do
    repeated :libraries, :message, 1, "maptool.AddOnLibraryListDto.AddOnLibraryEntryDto"
  end
  add_message "maptool.AddOnLibraryListDto.AddOnLibraryEntryDto" do
    optional :details, :message, 17, "maptool.AddOnLibraryDto"
    optional :md5_hash, :string, 18
  end
  add_message "maptool.AddOnLibraryEventsDto" do
    repeated :events, :message, 1, "maptool.AddOnLibraryEventsDto.Events"
    repeated :legacy_events, :message, 2, "maptool.AddOnLibraryEventsDto.Events"
  end
  add_message "maptool.AddOnLibraryEventsDto.Events" do
    optional :name, :string, 1
    optional :mts, :string, 2
    optional :js, :string, 3
  end
end

module Maptool
  AddOnLibraryDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AddOnLibraryDto").msgclass
  MTScriptPropertiesDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.MTScriptPropertiesDto").msgclass
  MTScriptPropertiesDto::Property = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.MTScriptPropertiesDto.Property").msgclass
  AddOnLibraryListDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AddOnLibraryListDto").msgclass
  AddOnLibraryListDto::AddOnLibraryEntryDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AddOnLibraryListDto.AddOnLibraryEntryDto").msgclass
  AddOnLibraryEventsDto = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AddOnLibraryEventsDto").msgclass
  AddOnLibraryEventsDto::Events = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AddOnLibraryEventsDto.Events").msgclass
end
