# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_types.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
require_relative 'data_transfer_objects_pb'
require_relative 'drawing_dto_pb'
require_relative 'gamedata_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "maptool.AddTopologyMsg" do
    optional :zone_guid, :string, 1
    optional :area, :message, 2, "maptool.AreaDto"
    optional :type, :enum, 3, "maptool.TopologyTypeDto"
  end
  add_message "maptool.BootPlayerMsg" do
    optional :player_name, :string, 1
  end
  add_message "maptool.BringTokensToFrontMsg" do
    optional :zone_guid, :string, 1
    repeated :token_guids, :string, 2
  end
  add_message "maptool.ChangeZoneDisplayNameMsg" do
    optional :zone_guid, :string, 1
    optional :name, :string, 2
  end
  add_message "maptool.ClearAllDrawingsMsg" do
    optional :zone_guid, :string, 1
    optional :layer, :string, 2
  end
  add_message "maptool.ClearExposedAreaMsg" do
    optional :zone_guid, :string, 1
    optional :global_only, :bool, 2
  end
  add_message "maptool.DrawMsg" do
    optional :zone_guid, :string, 1
    optional :pen, :message, 2, "maptool.PenDto"
    optional :drawable, :message, 3, "maptool.DrawableDto"
  end
  add_message "maptool.EditTokenMsg" do
    optional :zone_guid, :string, 1
    optional :token, :message, 2, "maptool.TokenDto"
  end
  add_message "maptool.PutTokenMsg" do
    optional :zone_guid, :string, 1
    optional :token, :message, 2, "maptool.TokenDto"
  end
  add_message "maptool.EnforceNotificationMsg" do
    optional :enforce, :bool, 1
  end
  add_message "maptool.EnforceZoneMsg" do
    optional :zone_guid, :string, 1
  end
  add_message "maptool.EnforceZoneViewMsg" do
    optional :zone_guid, :string, 1
    optional :x, :int32, 2
    optional :y, :int32, 3
    optional :scale, :double, 4
    optional :gm_width, :int32, 5
    optional :gm_height, :int32, 6
  end
  add_message "maptool.ExecFunctionMsg" do
    optional :target, :string, 1
    optional :source, :string, 2
    optional :function_name, :string, 3
    repeated :argument, :message, 4, "maptool.ScriptTypeDto"
  end
  add_message "maptool.ExecLinkMsg" do
    optional :link, :string, 1
    optional :target, :string, 2
    optional :source, :string, 3
  end
  add_message "maptool.ExposeFowMsg" do
    optional :zone_guid, :string, 1
    optional :area, :message, 2, "maptool.AreaDto"
    repeated :token_guid, :string, 3
  end
  add_message "maptool.ExposePcAreaMsg" do
    optional :zone_guid, :string, 1
  end
  add_message "maptool.GetAssetMsg" do
    optional :asset_id, :string, 1
  end
  add_message "maptool.GetZoneMsg" do
    optional :zone_guid, :string, 1
  end
  add_message "maptool.HeartbeatMsg" do
    optional :data, :string, 1
  end
  add_message "maptool.HideFowMsg" do
    optional :zone_guid, :string, 1
    optional :area, :message, 2, "maptool.AreaDto"
    repeated :token_guid, :string, 3
  end
  add_message "maptool.HidePointerMsg" do
    optional :player, :string, 1
  end
  add_message "maptool.MessageMsg" do
    optional :message, :message, 1, "maptool.TextMessageDto"
  end
  add_message "maptool.MovePointerMsg" do
    optional :player, :string, 1
    optional :x, :int32, 2
    optional :y, :int32, 3
  end
  add_message "maptool.PlayerConnectedMsg" do
    optional :player, :message, 1, "maptool.PlayerDto"
  end
  add_message "maptool.PlayerDisconnectedMsg" do
    optional :player, :message, 1, "maptool.PlayerDto"
  end
  add_message "maptool.PutAssetMsg" do
    optional :asset, :message, 1, "maptool.AssetDto"
  end
  add_message "maptool.PutLabelMsg" do
    optional :zone_guid, :string, 1
    optional :label, :message, 2, "maptool.LabelDto"
  end
  add_message "maptool.PutZoneMsg" do
    optional :zone, :message, 1, "maptool.ZoneDto"
  end
  add_message "maptool.RemoveAssetMsg" do
    optional :asset_id, :string, 1
  end
  add_message "maptool.RemoveLabelMsg" do
    optional :zone_guid, :string, 1
    optional :label_guid, :string, 2
  end
  add_message "maptool.RemoveTokenMsg" do
    optional :zone_guid, :string, 1
    optional :token_guid, :string, 2
  end
  add_message "maptool.RemoveTokensMsg" do
    optional :zone_guid, :string, 1
    repeated :token_guid, :string, 2
  end
  add_message "maptool.RemoveTopologyMsg" do
    optional :zone_guid, :string, 1
    optional :area, :message, 2, "maptool.AreaDto"
    optional :type, :enum, 3, "maptool.TopologyTypeDto"
  end
  add_message "maptool.RemoveZoneMsg" do
    optional :zone_guid, :string, 1
  end
  add_message "maptool.RenameZoneMsg" do
    optional :zone_guid, :string, 1
    optional :name, :string, 2
  end
  add_message "maptool.RestoreZoneViewMsg" do
    optional :zone_guid, :string, 1
  end
  add_message "maptool.SendTokensToBackMsg" do
    optional :zone_guid, :string, 1
    repeated :token_guids, :string, 2
  end
  add_message "maptool.SetBoardMsg" do
    optional :zone_guid, :string, 1
    optional :point, :message, 2, "maptool.IntPointDto"
    optional :asset_id, :string, 3
  end
  add_message "maptool.SetCampaignMsg" do
    optional :campaign, :message, 1, "maptool.CampaignDto"
  end
  add_message "maptool.SetCampaignNameMsg" do
    optional :name, :string, 1
  end
  add_message "maptool.SetFowMsg" do
    optional :zone_guid, :string, 1
    optional :area, :message, 2, "maptool.AreaDto"
    repeated :selected_tokens, :string, 3
  end
  add_message "maptool.SetLiveTypingLabelMsg" do
    optional :player_name, :string, 1
    optional :typing, :bool, 2
  end
  add_message "maptool.SetServerPolicyMsg" do
    optional :policy, :message, 1, "maptool.ServerPolicyDto"
  end
  add_message "maptool.SetTokenLocationMsg" do
    optional :zone_guid, :string, 1
    optional :token_guid, :string, 2
    optional :location, :message, 3, "maptool.IntPointDto"
  end
  add_message "maptool.SetVisionTypeMsg" do
    optional :zone_guid, :string, 1
    optional :vision, :enum, 2, "maptool.ZoneDto.VisionTypeDto"
  end
  add_message "maptool.SetZoneGridSizeMsg" do
    optional :zone_guid, :string, 1
    optional :x_offset, :int32, 2
    optional :y_offset, :int32, 3
    optional :size, :int32, 4
    optional :color, :int32, 5
  end
  add_message "maptool.SetZoneHasFowMsg" do
    optional :zone_guid, :string, 1
    optional :has_fow, :bool, 2
  end
  add_message "maptool.SetZoneVisibilityMsg" do
    optional :zone_guid, :string, 1
    optional :is_visible, :bool, 2
  end
  add_message "maptool.ShowPointerMsg" do
    optional :player, :string, 1
    optional :pointer, :message, 2, "maptool.PointerDto"
  end
  add_message "maptool.StartAssetTransferMsg" do
    optional :header, :message, 1, "maptool.AssetTransferHeaderDto"
  end
  add_message "maptool.StartTokenMoveMsg" do
    optional :player_id, :string, 1
    optional :zone_guid, :string, 2
    optional :key_token_id, :string, 3
    repeated :selected_tokens, :string, 4
  end
  add_message "maptool.StopTokenMoveMsg" do
    optional :zone_guid, :string, 1
    optional :key_token_id, :string, 2
  end
  add_message "maptool.ToggleTokenMoveWaypointMsg" do
    optional :zone_guid, :string, 1
    optional :key_token_id, :string, 2
    optional :point, :message, 3, "maptool.IntPointDto"
  end
  add_message "maptool.UndoDrawMsg" do
    optional :zone_guid, :string, 1
    optional :drawable_guid, :string, 2
  end
  add_message "maptool.UpdateAssetTransferMsg" do
    optional :chunk, :message, 1, "maptool.AssetChunkDto"
  end
  add_message "maptool.UpdateCampaignMsg" do
    optional :properties, :message, 1, "maptool.CampaignPropertiesDto"
  end
  add_message "maptool.UpdateCampaignMacrosMsg" do
    repeated :macros, :message, 1, "maptool.MacroButtonPropertiesDto"
  end
  add_message "maptool.UpdateDrawingMsg" do
    optional :zone_guid, :string, 1
    optional :pen, :message, 2, "maptool.PenDto"
    optional :drawing, :message, 3, "maptool.DrawnElementDto"
  end
  add_message "maptool.UpdateExposedAreaMetaMsg" do
    optional :zone_guid, :string, 1
    optional :token_guid, :message, 2, "google.protobuf.StringValue"
    optional :area, :message, 3, "maptool.AreaDto"
  end
  add_message "maptool.UpdateGmMacrosMsg" do
    repeated :macros, :message, 1, "maptool.MacroButtonPropertiesDto"
  end
  add_message "maptool.UpdateInitiativeMsg" do
    optional :list, :message, 1, "maptool.InitiativeListDto"
    optional :owner_permission, :message, 2, "google.protobuf.BoolValue"
  end
  add_message "maptool.UpdateTokenInitiativeMsg" do
    optional :zone_guid, :string, 1
    optional :token_guid, :string, 2
    optional :is_holding, :bool, 3
    optional :state, :message, 4, "google.protobuf.StringValue"
    optional :index, :int32, 5
  end
  add_message "maptool.UpdateTokenMoveMsg" do
    optional :zone_guid, :string, 1
    optional :key_token_id, :string, 2
    optional :point, :message, 3, "maptool.IntPointDto"
  end
  add_message "maptool.UpdateTokenPropertyMsg" do
    optional :zone_guid, :string, 1
    optional :token_guid, :string, 2
    optional :property, :enum, 3, "maptool.TokenUpdateDto"
    repeated :values, :message, 4, "maptool.TokenPropertyValueDto"
  end
  add_message "maptool.RemoveAddOnLibraryMsg" do
    repeated :namespaces, :string, 1
  end
  add_message "maptool.RemoveAllAddOnLibrariesMsg" do
  end
  add_message "maptool.AddAddOnLibraryMsg" do
    repeated :add_ons, :message, 1, "maptool.TransferableAddOnLibraryDto"
  end
  add_message "maptool.UpdateDataStoreMsg" do
    optional :store, :message, 1, "maptool.DataStoreDto"
  end
  add_message "maptool.UpdateDataMsg" do
    optional :type, :string, 1
    optional :namespace, :string, 2
    optional :value, :message, 3, "maptool.GameDataValueDto"
  end
  add_message "maptool.UpdateDataNamespaceMsg" do
    optional :data, :message, 1, "maptool.GameDataDto"
  end
  add_message "maptool.RemoveDataStoreMsg" do
  end
  add_message "maptool.RemoveDataNamespaceMsg" do
    optional :type, :string, 1
    optional :namespace, :string, 2
  end
  add_message "maptool.RemoveDataMsg" do
    optional :type, :string, 1
    optional :namespace, :string, 2
    optional :name, :string, 3
  end
end

module Maptool
  AddTopologyMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AddTopologyMsg").msgclass
  BootPlayerMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.BootPlayerMsg").msgclass
  BringTokensToFrontMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.BringTokensToFrontMsg").msgclass
  ChangeZoneDisplayNameMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ChangeZoneDisplayNameMsg").msgclass
  ClearAllDrawingsMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ClearAllDrawingsMsg").msgclass
  ClearExposedAreaMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ClearExposedAreaMsg").msgclass
  DrawMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.DrawMsg").msgclass
  EditTokenMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.EditTokenMsg").msgclass
  PutTokenMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PutTokenMsg").msgclass
  EnforceNotificationMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.EnforceNotificationMsg").msgclass
  EnforceZoneMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.EnforceZoneMsg").msgclass
  EnforceZoneViewMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.EnforceZoneViewMsg").msgclass
  ExecFunctionMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ExecFunctionMsg").msgclass
  ExecLinkMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ExecLinkMsg").msgclass
  ExposeFowMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ExposeFowMsg").msgclass
  ExposePcAreaMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ExposePcAreaMsg").msgclass
  GetAssetMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.GetAssetMsg").msgclass
  GetZoneMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.GetZoneMsg").msgclass
  HeartbeatMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.HeartbeatMsg").msgclass
  HideFowMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.HideFowMsg").msgclass
  HidePointerMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.HidePointerMsg").msgclass
  MessageMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.MessageMsg").msgclass
  MovePointerMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.MovePointerMsg").msgclass
  PlayerConnectedMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PlayerConnectedMsg").msgclass
  PlayerDisconnectedMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PlayerDisconnectedMsg").msgclass
  PutAssetMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PutAssetMsg").msgclass
  PutLabelMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PutLabelMsg").msgclass
  PutZoneMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.PutZoneMsg").msgclass
  RemoveAssetMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveAssetMsg").msgclass
  RemoveLabelMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveLabelMsg").msgclass
  RemoveTokenMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveTokenMsg").msgclass
  RemoveTokensMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveTokensMsg").msgclass
  RemoveTopologyMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveTopologyMsg").msgclass
  RemoveZoneMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveZoneMsg").msgclass
  RenameZoneMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RenameZoneMsg").msgclass
  RestoreZoneViewMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RestoreZoneViewMsg").msgclass
  SendTokensToBackMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SendTokensToBackMsg").msgclass
  SetBoardMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetBoardMsg").msgclass
  SetCampaignMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetCampaignMsg").msgclass
  SetCampaignNameMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetCampaignNameMsg").msgclass
  SetFowMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetFowMsg").msgclass
  SetLiveTypingLabelMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetLiveTypingLabelMsg").msgclass
  SetServerPolicyMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetServerPolicyMsg").msgclass
  SetTokenLocationMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetTokenLocationMsg").msgclass
  SetVisionTypeMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetVisionTypeMsg").msgclass
  SetZoneGridSizeMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetZoneGridSizeMsg").msgclass
  SetZoneHasFowMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetZoneHasFowMsg").msgclass
  SetZoneVisibilityMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.SetZoneVisibilityMsg").msgclass
  ShowPointerMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ShowPointerMsg").msgclass
  StartAssetTransferMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.StartAssetTransferMsg").msgclass
  StartTokenMoveMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.StartTokenMoveMsg").msgclass
  StopTokenMoveMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.StopTokenMoveMsg").msgclass
  ToggleTokenMoveWaypointMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.ToggleTokenMoveWaypointMsg").msgclass
  UndoDrawMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UndoDrawMsg").msgclass
  UpdateAssetTransferMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateAssetTransferMsg").msgclass
  UpdateCampaignMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateCampaignMsg").msgclass
  UpdateCampaignMacrosMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateCampaignMacrosMsg").msgclass
  UpdateDrawingMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateDrawingMsg").msgclass
  UpdateExposedAreaMetaMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateExposedAreaMetaMsg").msgclass
  UpdateGmMacrosMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateGmMacrosMsg").msgclass
  UpdateInitiativeMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateInitiativeMsg").msgclass
  UpdateTokenInitiativeMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateTokenInitiativeMsg").msgclass
  UpdateTokenMoveMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateTokenMoveMsg").msgclass
  UpdateTokenPropertyMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateTokenPropertyMsg").msgclass
  RemoveAddOnLibraryMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveAddOnLibraryMsg").msgclass
  RemoveAllAddOnLibrariesMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveAllAddOnLibrariesMsg").msgclass
  AddAddOnLibraryMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.AddAddOnLibraryMsg").msgclass
  UpdateDataStoreMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateDataStoreMsg").msgclass
  UpdateDataMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateDataMsg").msgclass
  UpdateDataNamespaceMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.UpdateDataNamespaceMsg").msgclass
  RemoveDataStoreMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveDataStoreMsg").msgclass
  RemoveDataNamespaceMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveDataNamespaceMsg").msgclass
  RemoveDataMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("maptool.RemoveDataMsg").msgclass
end
